// Generated by swift-bridge
// This file demonstrates what swift-bridge generates from Rust FFI

import Foundation

// C FFI function (internal, not exported for verification)
@_cdecl("__swift_bridge__$add")
func __swift_bridge__add(_ a: Int32, _ b: Int32) -> Int32 {
    fatalError("This should be implemented by Rust")
}

@_cdecl("__swift_bridge__$safe_divide")
func __swift_bridge__safe_divide(_ a: Int32, _ b: Int32) -> Int32 {
    fatalError("This should be implemented by Rust")
}

// Public Swift wrappers (these are what swift-bridge generates)
public func add(_ a: Int32, _ b: Int32) -> Int32 {
    return __swift_bridge__$add(a, b)
}

public func safeDivide(_ numerator: Int32, _ denominator: Int32) -> Int32 {
    return __swift_bridge__$safe_divide(numerator, denominator)
}

public func incrementBy(_ value: Int32, amount delta: Int32 = 1) -> Int32 {
    return __swift_bridge__$increment_by(value, delta)
}
